- name: config zones to DNS ns2
  template: 
    src: "etc/bind/named.conf.local.diff" 
    dest: "/tmp/named.conf.local.diff"
    # vars:
    #   ns1_ip: 10.128.10.11
- name: and patch DNS ns2
  ansible.posix.patch:
    src: /tmp/named.conf.local.diff
    dest: /etc/bind/named.conf.local