network:
    version: 2
    renderer: NetworkManager
    ethernets:
        {{interface_no}}:                      # Private network interface
            dhcp4: no
            dhcp6: no
            addresses:
                - {{interface_ip}}/{{interface_mask}}
            gateway4: {{interface_ip}}