- name: Android
  import_playbook: develop-android.yml
- name: Ansible
  import_playbook: develop-ansible.yml
- name: VSCode
  import_playbook: develop-vscode.yml
- name: JavaScript
  import_playbook: develop-lang-javascript.yml
- name: Haskell
  import_playbook: develop-lang-haskell.yml
- name: PHP
  import_playbook: develop-lang-php.yml
- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      vars:
        package_name: developer
        packages:
#            - cpp-dependencies
            - graphviz
      community.general.snap:
        name:
          - cmake
          - eclipse
          - postman
    - role: packages
      vars:
        package_name: kernel-developer
        packages:
            # - linux-headers-$(uname -r)
            - ncurses-dev
            # - kernel-package
            # - qt4-dev-tools
            - pkg-config
            - build-essential
    # make menuconfig and make xconfig