- name: Android
  import_playbook: develop-android.yml
- name: Ansible
  import_playbook: develop-ansible.yml
- name: JavaScript
  import_playbook: develop-lang-javascript.yml
- name: Haskell
  import_playbook: develop-lang-haskell.yml
- name: PHP
  import_playbook: develop-lang-php.yml
- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      when: ansible_facts['os_family'] == 'Debian'
      vars:
        package_name: APT
        packages:
            - software-properties-common
            - apt-transport-https
    - role: repo-add
      vars:
        repo_name: vscode
        repo_key_url: https://packages.microsoft.com/keys/microsoft.asc
        repo: https://packages.microsoft.com/repos/vscode
    - role: packages
      vars:
        package_name: developer
        packages:
            - code
#            - cpp-dependencies
            - graphviz
      community.general.snap:
        name:
          - cmake
          - eclipse
    - role: packages
      vars:
        package_name: kernel-developer
        packages:
            # - linux-headers-$(uname -r)
            - ncurses-dev
            # - kernel-package
            # - qt4-dev-tools
            - pkg-config
            - build-essential
    # make menuconfig and make xconfig