- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      when: ansible_facts['os_family'] == 'Debian'
      vars:
        package_name: APT
        packages:
            - apt-transport-https
            - ca-certificates
            - gnupg-agent
            - software-properties-common
    - role: repo-add
      vars:
        repo_name: docker
        repo_key_url: https://download.docker.com/linux/ubuntu/gpg
        repo: https://download.docker.com/linux/ubuntu
        repo_id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
# fatal: [ns1]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
    - role: packages
      vars:
        package_name: docker
        packages:
            - docker-ce
            - docker-ce-cli
            - containerd.io
    - role: docker-compose
    - role: user-to-group
      vars:
        group: docker
        user: "{{sudo_user}}"
    - role: packages
      vars:
        package_name: Python
        packages:
            - python3-distutils
    - role: pip
      vars:
        package_name: pyyaml
        packages:
            - pyyaml
    - role: service-restart
      vars:
        service: docker
    - role: packages
      vars:
        package_name: Alpine Linux package management
        packages:
            - apktool