- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      vars:
        package_name: network tools
        packages:
           - gnome-network-admin
           - network-manager-gnome
          #  nm-connection-editor
    - role: packages
      vars:
        package_name: rsync
        packages:
           - grsync
    - role: packages
      vars:
        package_name: desktop-twitch-codecses
        packages:
            - gnome-twitch-player-backend-gstreamer-cairo
            - gnome-twitch-player-backend-gstreamer-clutter
            - gnome-twitch-player-backend-gstreamer-opengl
    - role: packages
      vars:
        package_name: desktop-gnome
        packages:
            - unzip
            - gnome
            - gnome-shell
            - gnome-shell-extensions
            - gnome-shell-extension-prefs
            - gnome-shell-extension-autohidetopbar
            - gnome-shell-extension-gsconnect
            - chrome-gnome-shell
    - role: packages-remove
      vars:
        package_name: desktop-gnome-remove-games
        packages:
            - aisleriot
            - five-or-more
            - four-in-a-row
            - hitori
            - gnome-klotski
            - gnome-mahjongg
            - gnome-mines
            - gnome-nibbles
            - gnome-robots
            - gnome-sudoku
            - gnome-taquin
            - gnome-tetravex
            - lightsoff
            - quadrapassel
            - swell-foop
            - tali
    - role: ansible-role-customize-gnome
      vars:
        gnome_user: "{{sudo_user}}"
        gnome_extensions:
          - id: 1139 # apt-update-indicator
          # - id: 2197 # new-apt-update-indicator
          - id: 945 # cpu-power-manager
          - id: 82 # cpu-temperature-indicator
          - id: 307 # dash-to-dock
          - id: 1036 # extensions
          - id: 1166 # extension-update-notifier
          - id: 750 # openweather
          - id: 836 # internet-radio
          - id: 154 # gmail-notify
          # - id: 1247 # gnome-radio
          - id: 336 # hardware-sensors-indicator
          - id: 921 # multi-monitors-add-on
          - id: 104 # netspeed
          - id: 1505 # new-mail-indicator
          - id: 214 # pidgin-conversation-integration
          - id: 170 # pidgin-peristent-notification
          - id: 473 # remmina-search-provider
          - id: 430 # shell-utilities
          - id: 941 # show-ip
          - id: 906 # sound-output-device-chooser
          - id: 73 # ssh-search-provider
          - id: 9 # systemmonitor
          - id: 365 # transmission-daemon-indicator
        gnome_dconf:
          - key: /org/gnome/desktop/background/show-desktop-icons
            value: "true"
          - key: /org/gnome/shell/development-tools
            value: "true"
          # - key: /org/gnome/shell/enabled-extensions
          #   value: ['new-apt-update-indicator@hamburgerjungejr', 'cpupower@mko-sl.de', 'extensions@abteil.org', 'openweather-extension@jenslody.de', 'radio@hslbck.gmail.com', 'gnome-radio@gnome-shell-exstensions.fffilo.github.com', 'netspeed@hedayaty.gmail.com']
    - role: packages
      vars:
        package_name: images
        packages:
            - shotwell
    - role: packages
      vars:
        package_name: mp4
        packages:
            - vlc
            - ubuntu-restricted-extras
      community.general.snap:
        name: shotcut
        classic: yes
    - role: packages
      vars:
        package_name: pdf
        packages:
            - gimp
            - inkscape