- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      vars:
        package_name: network tools
        packages:
           - gnome-network-admin
           - network-manager-gnome
          #  nm-connection-editor
    - role: packages
      vars:
        package_name: grsync
        packages:
           - grsync
    - role: packages
      vars:
        package_name: desktop-twitch-codecses
        packages:
            - gnome-twitch-player-backend-gstreamer-cairo
            - gnome-twitch-player-backend-gstreamer-clutter
            - gnome-twitch-player-backend-gstreamer-opengl
    - role: packages
      vars:
        package_name: desktop-gnome
        packages:
            - gnome
            - gnome-shell
    - role: packages-remove
      vars:
        package_name: desktop-gnome-remove-games
        packages:
            - aisleriot
            - five-or-more
            - four-in-a-row
            - hitori
            - gnome-klotski
            - gnome-mahjongg
            - gnome-mines
            - gnome-nibbles
            - gnome-robots
            - gnome-sudoku
            - gnome-taquin
            - gnome-tetravex
            - lightsoff
            - quadrapassel
            - swell-foop
            - tali
    - role: packages
      vars:
        package_name: images
        packages:
            - shotwell
    - role: packages
      vars:
        package_name: mp4
        packages:
            - vlc
            - ubuntu-restricted-extras
      community.general.snap:
        name: shotcut
        classic: yes
    - role: packages
      vars:
        package_name: pdf
        packages:
            - gimp
            - inkscape