- name: Desktop
  import_playbook: packages-desktop.yml
- name: Gnome
  import_playbook: packages-gnome.yml
- name: Network
  import_playbook: packages-network.yml
- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: pip
      vars:
        package_name: pythonpy
        packages:
            - pythonpy
            - libusb1
    # echo "alias py='pythonpy'" >> ~/.bashrc
    # /home/noud/.local/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working