- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      vars:
        package_name: desktop-gnome-extensions
        packages:
            - unzip
            - gnome-shell-extensions
            - gnome-shell-extension-prefs
            - gnome-shell-extension-autohidetopbar
            - gnome-shell-extension-gsconnect
            - chrome-gnome-shell
    - role: petermosmans.customize-gnome
      vars:
        gnome_user: "{{sudo_user}}"
        gnome_extensions:
          - id: 1139
            name: apt-update-indicator
            url: https://extensions.gnome.org/extension/1139/apt-update-indicator/
          # - id: 2197 # new-apt-update-indicator
          - id: 945
            name: cpu-power-manager
            url: https://extensions.gnome.org/extension/945/cpu-power-manager/
          - id: 82
            name: cpu-temperature-indicator
            url: https://extensions.gnome.org/extension/82/cpu-temperature-indicator/
          - id: 307
            name: dash-to-dock
            url: https://extensions.gnome.org/extension/307/dash-to-dock/
          - id: 1036
            name: extensions
            url: https://extensions.gnome.org/extension/1036/extensions/
          - id: 1166
            name: extension-update-notifier
            url: https://extensions.gnome.org/extension/1166/extension-update-notifier/
          - id: 750
            name: openweather
            url: https://extensions.gnome.org/extension/750/openweather/
          - id: 836
            name: internet-radio
            url: https://extensions.gnome.org/extension/836/internet-radio/
          - id: 154
            name: gmail-notify
            url: https://extensions.gnome.org/extension/154/gmail-notify/
          # - id: 1247 # gnome-radio
          - id: 336
            name: hardware-sensors-indicator
            url: https://extensions.gnome.org/extension/336/hardware-sensors-indicator/
          - id: 921
            name: multi-monitors-add-on
            url: https://extensions.gnome.org/extension/921/multi-monitors-add-on/
          - id: 104
            name: netspeed
            url: https://extensions.gnome.org/extension/104/netspeed/
          - id: 1505
            name: new-mail-indicator
            url: https://extensions.gnome.org/extension/1505/new-mail-indicator/
          - id: 214
            name: pidgin-conversation-integration
            url: https://extensions.gnome.org/extension/214/pidgin-conversation-integration/
          - id: 170
            name: pidgin-peristent-notification
            url: https://extensions.gnome.org/extension/170/pidgin-peristent-notification/
          - id: 473
            name: remmina-search-provider
            url: https://extensions.gnome.org/extension/473/remmina-search-provider/
          - id: 430
            name: shell-utilities
            url: https://extensions.gnome.org/extension/430/shell-utilities/
          - id: 941
            name: show-ip
            url: https://extensions.gnome.org/extension/941/show-ip/
          - id: 906
            name: sound-output-device-chooser
            url: https://extensions.gnome.org/extension/906/sound-output-device-chooser/
          - id: 73
            name: ssh-search-provider
            url: https://extensions.gnome.org/extension/1714/ssh-search-provider-reborn/
          - id: 9
            name: systemmonitor
            url: https://extensions.gnome.org/extension/120/system-monitor/
          - id: 365
            name: transmission-daemon-indicator
            url: https://extensions.gnome.org/extension/365/transmission-daemon-indicator/
        gnome_dconf:
          - key: /org/gnome/desktop/background/show-desktop-icons
            value: "true"
          - key: /org/gnome/shell/development-tools
            value: "true"
          # - key: /org/gnome/shell/enabled-extensions
          #   value: ['new-apt-update-indicator@hamburgerjungejr', 'cpupower@mko-sl.de', 'extensions@abteil.org', 'openweather-extension@jenslody.de', 'radio@hslbck.gmail.com', 'gnome-radio@gnome-shell-exstensions.fffilo.github.com', 'netspeed@hedayaty.gmail.com']