- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      vars:
        package_name: screen recording
        packages:
           - kazam