- name: create directory for Git checkout
  file:
    path: {{repo_dir}}
    state: directory
- name: Git checkout
  git:
    repo: {{repo}}
    dest: {{repo_dir}}
- name: Move git checkout to correct name
  command: mv {{repo_dir}}/{{repo_name}} {{repo_dir}}/{{repo_dir_name}}