- name: Check that {{iso_file_name}} exists
  stat:
    path: "/home/{{sudo_user}}/Downloads/{{ tarball }}.tar.gz"
  register: stat_result
- name: Download tarball
  when: not stat_result.stat.exists
  get_url:
    url: "{{ url_path }}/{{ tarball }}.tar.gz"
    dest: "/home/{{ sudo_user }}/Downloads/"
- name: create tmp dir
  file:
    path: "/tmp/{{ tmp_path }}"
    state: directory
- name: Unarchive source
  unarchive:
    src: "/home/{{ sudo_user }}/Downloads/{{ tarball }}.tar.gz"
    dest: "/tmp/{{ tmp_path }}"