- name: Bump APT content
  # @todo test
  # cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux
  # apt update # the list of available
- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
# apt update # actually installs
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes # cache_valid_time=3600